version: "3.1"
services:
  www:
    image: cdecarlos/php-apache:7.2
    # image: cdecarlos/php-apache:7.0 # Build
    ports:
      - "8080:80"
    volumes:
      - ./www:/var/www/html
    networks:
      - default
    links:
      - db
  db:
    image: mysql:8.0
    # platform: linux/x86_64 # Apple M1
    ports:
      - "3307:3306"
    command: ['mysqld', '--character-set-server=utf8', '--collation-server=utf8_unicode_ci', '--default-authentication-plugin=mysql_native_password']
    environment:
      MYSQL_DATABASE: docker_db
      MYSQL_USER: docker_user
      MYSQL_PASSWORD: docker_pass
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./dump_db:/docker-entrypoint-initdb.d
      - ./conf_db:/etc/mysql/conf.d
      - ./persistent_db:/var/lib/mysql
    networks:
      - default
  phpmyadmin:
    image: phpmyadmin
    environment:
      UPLOAD_LIMIT: 100M
    links:
      - db:db
    depends_on:
      - db
    ports:
      - 8090:80
